baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Endrol Blog'
theme = "papermod"

[pagination]
pagerSize = 5

[params]
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true

[params.homeInfoParams]
Title = "Welcome to Endrol Blog"
Content = "Own blogs for learning"

[[params.socialIcons]]
name = "twitter"
url = "https://x.com/home"

[[params.socialIcons]]
name = "github"
url = "https://github.com/endrol/endrol.github.io"

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 30
